# Generated by Django 4.1.3 on 2023-01-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totel',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
