# Generated by Django 4.1.3 on 2023-01-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_totel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totel',
            new_name='total',
        ),
    ]
